// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfdXsvv0684q38QdyGaYGjMf5P0oKkscM',
    appId: '1:160991793775:web:77a9eeebc1ab95ac7cf39a',
    messagingSenderId: '160991793775',
    projectId: 'invoice-generator-2005',
    authDomain: 'invoice-generator-2005.firebaseapp.com',
    storageBucket: 'invoice-generator-2005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpLF5iY4XAgGaJBeCpJ11k1MKCLGzMLLw',
    appId: '1:160991793775:android:270fc5dffba4231a7cf39a',
    messagingSenderId: '160991793775',
    projectId: 'invoice-generator-2005',
    storageBucket: 'invoice-generator-2005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEZx2DW_1sLNwoba2JbqUAg1UlOkaatk',
    appId: '1:160991793775:ios:d0d62f211ed416187cf39a',
    messagingSenderId: '160991793775',
    projectId: 'invoice-generator-2005',
    storageBucket: 'invoice-generator-2005.firebasestorage.app',
    iosBundleId: 'com.example.appPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeEZx2DW_1sLNwoba2JbqUAg1UlOkaatk',
    appId: '1:160991793775:ios:d0d62f211ed416187cf39a',
    messagingSenderId: '160991793775',
    projectId: 'invoice-generator-2005',
    storageBucket: 'invoice-generator-2005.firebasestorage.app',
    iosBundleId: 'com.example.appPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfdXsvv0684q38QdyGaYGjMf5P0oKkscM',
    appId: '1:160991793775:web:4fa929cee80c10b17cf39a',
    messagingSenderId: '160991793775',
    projectId: 'invoice-generator-2005',
    authDomain: 'invoice-generator-2005.firebaseapp.com',
    storageBucket: 'invoice-generator-2005.firebasestorage.app',
  );
}